x-app: &default-app
  build: .
  env_file: .env
  depends_on:
    - redis
    - postgres

services:
  web:
    <<: *default-app
    command: gunicorn yamllms.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - PRODUCTION=false
      - DEBUG=true

  worker:
    <<: *default-app
    command: python manage.py rqworker
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
